# Generated by Django 3.1.1 on 2020-09-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
    ]
