# Generated by Django 3.1.1 on 2020-10-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='department_created',
            field=models.DateField(auto_now=True),
        ),
    ]
