# Generated by Django 3.1.1 on 2020-10-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_departments_department_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
